version: "3.9"

services:
  web:
    build: .
    container_name: teabe_django
    command:
      - sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8000

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html/${PROJECT}
